In [8]:
from lib.mrnetdata import *
from lib.plot import *
from lib.MLMethod import *
from lib.kneedata import *
from lib.evaluator import *
from lib.shapes import *
from lib.vggModel import *
import pickle

In [9]:
#data.scans[:][:][:][70-5:70+5:6]
with open("pickled/mrnet_abnormal_train.pck",'rb') as fp:   
    data = pickle.load(fp)            

In [12]:
h = Haralicks(compute_dog=False)
h.featureSelector(5,50,data.scans,data.labels,"value",True)       #5

[0.52 0.44 0.5  0.54 0.56 0.48 0.46 0.52 0.5  0.52 0.52 0.46 0.44 0.54
 0.52 0.48 0.48 0.52 0.5  0.46 0.46 0.48 0.48 0.52 0.52 0.52 0.52 0.52
 0.52 0.5  0.52 0.52 0.54 0.54 0.46 0.56 0.54 0.46 0.54 0.46 0.44 0.56
 0.5  0.52 0.54 0.5  0.48 0.54 0.54 0.46 0.46 0.52 0.52 0.48 0.54 0.5
 0.52 0.44 0.5  0.52 0.52 0.54 0.46 0.52 0.5  0.56 0.5  0.5  0.54 0.46
 0.46 0.52 0.48 0.5  0.48 0.56 0.54 0.46 0.5  0.54 0.5  0.52 0.44 0.52
 0.54 0.52 0.46 0.5  0.5  0.52 0.52 0.46 0.44 0.44 0.56 0.5  0.5  0.5
 0.52 0.52]
[0.62 0.42 0.44 0.64 0.4  0.38 0.4  0.62 0.62 0.48 0.62 0.5  0.42 0.64
 0.64 0.62 0.54 0.6  0.58 0.5  0.62 0.62 0.6  0.4  0.64 0.62 0.64 0.62
 0.54 0.64 0.42 0.62 0.62 0.64 0.64 0.68 0.62 0.4  0.44 0.4  0.56 0.44
 0.52 0.64 0.62 0.4  0.48 0.62 0.58 0.54 0.54 0.42 0.54 0.62 0.64 0.48
 0.6  0.6  0.48 0.56 0.64 0.62 0.42 0.62 0.64 0.64 0.44 0.48 0.5  0.42
 0.44 0.42 0.62 0.52 0.58 0.58 0.6  0.66 0.48 0.64 0.62 0.4  0.56 0.5
 0.66 0.62 0.42 0.62 0.62 0.4  0.62 0.44 0.62 0.48 0.44 0.6  0.6  0.

In [4]:
#data = SimpleShapeData()
data = KneeData()
data.loadData(from_original_files=True,pickled_db_path="pickled/erik_train.pck",path='/home/dawit/Datalogi/BachelorProjekt/data/erik/train_data/')
m = VGGModel()
#m.fit(data.getScansAtSlice(three_slices=True),data.labels,"ishealthy",True)
e = Evaluator(data_obj=data,method_obj=m,load_as_slice=True,three_slices=True)
#d = data.vggData("shape","triangle")

Instructions for updating:
Colocations handled automatically by placer.
initialization finished


In [4]:
#for i in e.scans:
#    print(i.shape)

In [5]:
e.query(0,5)

([0, 38, 56, 64, 55],
 [2.441266769892536e-05,
  29.243480682373047,
  30.16129493713379,
  30.884754180908203,
  31.134431838989258])

In [8]:
m.extractFromBatch(data.scans)

In [9]:
m.matrix[0].shape

(100,)

In [5]:
m.model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [6]:
m.matrix[0].shape

IndexError: list index out of range

In [19]:
arr = np.array([[1,2],[1,2]])
arr = np.expand_dims(arr,axis=2)
arr = np.repeat(arr,3,2)

arr.shape
arr

array([[[1, 1, 1],
        [2, 2, 2]],

       [[1, 1, 1],
        [2, 2, 2]]])

In [6]:
vgg_model = VGG16(weights='imagenet', include_top=True)
vgg_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [5]:
d[0][0].shape

(224, 224, 3)

In [6]:
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.layers import Flatten
from keras.models import Model
from keras import optimizers
from keras.layers.core import Flatten, Dense, Dropout

import numpy as np
#vgg_model = Model(inputs=vgg_model.input, outputs=f0)
#vgg_model.predict(d[0][0])


vgg_model = VGG16(weights='imagenet', include_top=True)
vgg_model.layers.pop()
#vgg_model.layers.Add(Dense(2, activation='softmax'))
#layer_name = 'fc2'
#connected_layer = vgg_model.get_layer(layer_name)
#old_out = Flatten()()

out = Dense(2, activation='softmax')(vgg_model.output)
model = Model(inputs=vgg_model.input,
                                 outputs=out)
#vgg_model = VGG16()
sgd = optimizers.SGD(lr=1e-3, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy'])

#vgg_model.fit(d[0],d[1])
#vgg_model.summary()
#layer_name = 'fc2'
#intermediate_layer_model = Model(inputs=vgg_model.input,
#                                 outputs=vgg_model.get_layer(layer_name).output)
#image = d[0][0]
#image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
#intermediate_output = intermediate_layer_model.predict(image)
#intermediate_output

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
#intermediate_output.flatten().shape
image = d[0][0]
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
image = np.append(image ,image,axis=0)
#model.summary()
p = model.predict(image)

p.shape
p


array([[0.50095177, 0.49904823],
       [0.50095177, 0.49904823]], dtype=float32)

In [ ]:
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np

class VGG16:
    def __init__(self):
        self.matrix = []
        self.model = VGG16(weights='imagenet', include_top=False,classes=2)

    def extractFeatures(self,img,feature_




lib
Name
Last Modified

indices=None):      
        if self.compute_dog:
            img = mh.dog(img)
        features= mh.features.haralick(img).mean(0)
        if feature_indices == None:
            feature_indices = self.selected_features
        retval = [features[i] for i in feature_indices]
        return retval
    
    def distance(self,vec1,vec2):
        return scipy.spatial.distance.euclidean(vec1,vec2)
    
    def extractFromBatch(self,batch,feature_indices=None, pickled_db_path="haralickfeatures.pck"):
        self.matrix = []
        for i in batch:
            self.matrix.append(self.extractFeatures(i,feature_indices))
#            print(i.shape)
        with open(pickled_db_path,'wb') as fp:   
            pickle.dump(self.matrix,fp)      
    
    def loadFeatures(self,pickled_db_path="haralickfeatures.pck"):
        with open(pickled_db_path,'rb') as fp:
            self.matrix = pickle.load(fp)
        
            
    def countClassificationRatio(self,label_indices,label_name,label_value,labels):
        relevant_count = 0
        non_relevant_count = 0 
        for index in label_indices:
            if labels[index][label_name] == label_value:
                relevant_count += 1
            else:
                non_relevant_count += 1
                
        return relevant_count / (len(label_indices))
    
    def featureSelector(self,size,K,scans,labels,relevant_label,label_value):
        selection = []
        count = len(scans)
        

        binary_labels = [1 if i[relevant_label]==label_value else 0 for i in labels ]       
        best_auc = 0.0
        while len(selection) < size:
            index_auc = []
            for i in range(13):
#                print(i)
                if i in selection:
                    continue
                temp_selection = selection + [i]
                probabilities = np.zeros((count),dtype=np.float)
                #format database to same vector size
                self.extractFromBatch(scans,feature_indices=temp_selection)
                for m_iter in range(count):
                    retrieved_indices,distances = self.query(scans[m_iter],K+1,feature_indices=temp_selection)           
                    retrieved_indices = retrieved_indices[1:]           
        #            thresh_index = 0
        #            threshold = 0.0
        #            while threshold < 1.0:
                    ratio = self.countClassificationRatio(retrieved_indices,relevant_label,labels[m_iter][relevant_label],labels)
                    if not labels[m_iter][relevant_label] == label_value:
                        ratio = 1-ratio
                    probabilities[m_iter] = ratio
                
                auc = roc_auc_score(binary_labels,probabilities)   
                index_auc.append((i,auc))
            index_auc.sort(reverse=True,key=lambda k: k[1])
#            print(index_auc)
            print(index_auc)
            best_feature = index_auc[0][0]
            local_best_auc = index_auc[0][1]
            if local_best_auc <= best_auc:
                break
            else:
                best_auc = local_best_auc
            selection.append(best_feature)
            
#        selection.sort()
        self.selected_features = selection
        print(selection)
        print("finished Haralick Feature selection")
#               
        
        
    def query(self,query_img,k,feature_indices=None):
        if self.matrix is []:
            print("empty feature matrix")
            return []
        query_img_features = self.extractFeatures(query_img,feature_indices)
        distances_and_indices = []
        for index,database_img_features in enumerate(self.matrix):
            distance = self.distance(query_img_features,database_img_features)
            distances_and_indices.append((distance,index))
        distances_and_indices.sort(key=lambda pair:pair[0])
        relevant_dist_and_indices = distances_and_indices[:k]
        retval_indices = []
        retval_dist = []
        for i in relevant_dist_and_indices:
            dist,index = i
            retval_indices.append(index)
            retval_dist.append(dist)
        return retval_indices,retval_dist

In [10]:
base_path = "/home/dawit/Datalogi/BachelorProjekt/data/"
mrnet_train_ab = MRnetData()
mrnet_train_ab.loadData(from_original_files=True,pickled_db_path=base_path+"../jub/lib/mrnet/abnormal_train.pck",path_scans=base_path+"extracted_MR/meniscus/train",\
               path_labels=base_path+"MRNet-v1.0/train-abnormal.csv")
#mrnet.prepareTrainingData()

mrnet_test_ab = MRnetData()
mrnet_test_ab.loadData(from_original_files=True,pickled_db_path=base_path+"../jub/lib/mrnet/abnormal_valid.pck",path_scans=base_path+"extracted_MR/meniscus/test",\
               path_labels=base_path+"MRNet-v1.0/valid-abnormal.csv")
#mrnet_test_ab.prepareTrainingData()
#mrnet_train_acl = mrnet.genSameScansDifferentLabels(path_labels=base_path+"MRNet-v1.0/train-acl.csv")
#mrnet_train_meniscus = mrnet.genSameScansDifferentLabels(path_labels=base_path+"MRNet-v1.0/train-meniscus.csv")

#test_data = KneeData()
#test_data.loadData(from_original_files=True,pickled_db_path="scans_and_labels_test.pck",path='/home/dawit/Datalogi/BachelorProjekt/data/test_data/')
#test_data.prepareTrainingData()

In [11]:
depth = [i.shape[2] for i in mrnet_train_ab.scans]
print(min(depth)) #21 17
print(max(depth)) #45 46

18
47


In [ ]:
mrnet_test_ab.loadData(from_original_files=True,pickled_db_path=base_path+"../jub/lib/mrnet/abnormal_train.pck",path_scans=base_path+"extracted_MR/abnormal/train",\
               path_labels=base_path+"MRNet-v1.0/train-abnormal.csv")
mrnet.prepareTrainingData()

In [3]:
ml_method = ConvolutionMethod(mrnet_acl,load_prev_model=False,input_size=2)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Time usage: 0:00:00


In [4]:
e_ML_shape  = Evaluator(data_obj=mrnet_acl,method_obj=ml_method,load_as_slice=True)

initialization finished


In [7]:
print(e_ML_shape.MAP(mrnet.count,5,["value"]))
#plotter = Plotter()
#plotter.plotSingleShape(mrnet.getScansAtSlice()[0])
#mrnet.labels

Elapsed time: 69.12520146369934
0.36300000000000004


In [4]:
for i in mrnet.scans:
    print(i.shape)

(256, 256, 32)
(256, 256, 32)
(256, 256, 36)
(256, 256, 20)
(256, 256, 30)
(256, 256, 38)
(256, 256, 26)
(256, 256, 36)
(256, 256, 26)
(256, 256, 26)


In [5]:
mrnet.categorizeImages()

{'valueTrue': [0, 1, 4, 7, 9], 'valueFalse': [2, 3, 5, 6, 8]}

In [6]:
mrnet.getScansAtSlice()[0].shape

(256, 256)

In [7]:
mrnet.prepareTrainingData()

In [8]:
mrnet.getTrainingData(1)

(array([[[0, 0, 1, ..., 2, 1, 0],
         [0, 0, 1, ..., 2, 1, 0],
         [0, 0, 4, ..., 1, 0, 0],
         ...,
         [0, 0, 3, ..., 4, 2, 0],
         [0, 0, 3, ..., 6, 0, 0],
         [0, 0, 3, ..., 5, 1, 0]]], dtype=int32), array([[1., 0.]]))